### ISSUE TITLE
Visualization breaks when zoomed in

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/d3.cartodb#1]
http://cartodb.github.io/d3.cartodb/test.html

With initial zoom level:

![us1](https://cloud.githubusercontent.com/assets/498023/9990565/aa4356b2-6062-11e5-9cad-0243f0d6958f.png)

After zooming in:

![us2](https://cloud.githubusercontent.com/assets/498023/9990572/b54abaa0-6062-11e5-887c-73b080b64264.png)

Notice the _Uncaught TypeError: f.on is not a function_ error too.

**Comment by javisantana** [comment]
the fix does not fix the javascript error, only the geometry being cut
