### ISSUE TITLE
points are cut in tile edges

### ISSUE THREAD

**Issue by javisantana** [CartoDB/d3.cartodb#111]
- open examples/widths.html
- see bubbles being cut in the edges 
  ![screen shot 2016-02-22 at 4 09 26 pm](https://cloud.githubusercontent.com/assets/30147/13222096/ab1f4bb4-d97e-11e5-9e00-cb52ab6e5a3e.png)

**Comment by fdansv** [comment]
Fixed in windshaft issue above.
