### ISSUE TITLE
basic font support not working

### ISSUE THREAD

**Issue by javisantana** [CartoDB/d3.cartodb#112]
- open https://team.cartodb.com/u/javi/api/v2/viz/09a6d098-5fbe-11e5-b577-0e853d047bba/viz.json?callback=vizjson with the viz.json viewer

fonts are not shown are should be as close as possible to the image

![img](https://cartocdn-ashbu.global.ssl.fastly.net/javi/api/v1/map/static/named/tpl_09a6d098_5fbe_11e5_b577_0e853d047bba/560/300.png)

**Comment by fdansv** [comment]
This was fixed in #123
