### ISSUE TITLE
Very slow loading time and wrong numbers on widgets

### ISSUE THREAD

**Issue by saleiva** [CartoDB/d3.cartodb#129]
Test https://team.cartodb.com/u/saleiva/editor/58926788-2bdb-11e5-bd1e-0e0c41326911/embed?vector=true vs https://team.cartodb.com/u/saleiva/editor/58926788-2bdb-11e5-bd1e-0e0c41326911/embed

**Comment by fdansv** [comment]
> Very slow loading time
- https://github.com/CartoDB/Windshaft/issues/450
- https://github.com/CartoDB/d3.cartodb/issues/139

> Wrong numbers on widgets

Histogram data has had a few fixes in https://github.com/CartoDB/cartodb.js/pull/1181

**Comment by fdansv** [comment]
Closing this in favour of the issues above.
