### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rochoa** [CartoDB/d3.cartodb#145]

**Comment by fdansv** [comment]
Added in 1482f89fd20e96d7799185391acc278bf41c05ca

**Comment by rochoa** [comment]
Please, add it to the package.json also :pray:

**Comment by fdansv** [comment]
@rochoa it was there already, unless I'm missing something? https://github.com/CartoDB/d3.cartodb/blob/gh-pages/package.json#L24

**Comment by rochoa** [comment]
Oh, I see. I was complaining because npm was complaining as well:

```
npm WARN package.json d3.cartodb@1.0.1 No license field.
```

I'm gonna fix it :+1: Thanks!
