### ISSUE TITLE
module.export

### ISSUE THREAD

**Issue by rochoa** [CartoDB/d3.cartodb#15]
We need to review what we should [export](https://github.com/CartoDB/d3.cartodb/blob/a87f33fe68d868da2a8f3567da9294744c30e432/src/index.js#L3-L7). In other words: what the public API must be.

**Comment by rochoa** [comment]
Based on what are you closing this issue?

**Comment by fdansv** [comment]
This issue is from way before we cleaned up and arranged exports:

https://github.com/CartoDB/d3.cartodb/blob/gh-pages/src/index.js

**Comment by rochoa** [comment]
What is the public API remains unanswered.

For instance, does it makes sense to expose the `net` namespace?

I mean, at the end this is the very same as: https://github.com/CartoDB/d3.cartodb/issues/63
