### ISSUE TITLE
widgets data does not match with bbox

### ISSUE THREAD

**Issue by javisantana** [CartoDB/d3.cartodb#159]
![screen shot 2016-04-20 at 7 43 01 pm](https://cloud.githubusercontent.com/assets/30147/14684517/9d8d34fe-0730-11e6-842c-d5eb87ce198f.png)
widgets should be show full of green (no filters, full bbox)

**Comment by rochoa** [comment]
@javisantana do you mind sharing viz/dataset?

**Comment by fdansv** [comment]
@rochoa this is probably because d3.cartodb is not handling GeometryCollections properly, so when the viewport gets far away, features disappear.

**Comment by fdansv** [comment]
This was fixed in https://github.com/CartoDB/d3.cartodb/commit/ea0b6a4cb5a01504fee5931bbb8a6c9640778e12
