### ISSUE TITLE
tile buffer fails with bubble map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/d3.cartodb#160]
https://team.cartodb.com/u/saleiva/editor/b310d3e6-e362-11e4-9987-0e018d66dc29/embed?vector=true

**Comment by fdansv** [comment]
Yep! I believe this is happening because at the moment we're not changing the buffer size dynamically. Instead, the tiler is operating with a fixed buffer size (16px I think). @rochoa is there an easy way of changing that?

**Comment by rochoa** [comment]
WIP https://github.com/CartoDB/Windshaft/pull/475

**Comment by rochoa** [comment]
Maps API now supports `Map { buffer-size: ...; }` however this won't work until https://github.com/CartoDB/d3.cartodb/issues/178 is fixed.

**Comment by fdansv** [comment]
Fixed in #186
