### ISSUE TITLE
d3 cartocss rules are different from mapnik ones on comp-ops

### ISSUE THREAD

**Issue by saleiva** [CartoDB/d3.cartodb#161]
marker-comp-op: multiply; -> Mapnik
comp-op: multiply; -> d3.cartodb

we should unify or make the parser to make the conversion

**Comment by rochoa** [comment]
@fdansv is this fixed as per https://github.com/CartoDB/d3.cartodb/pull/169?

**Comment by fdansv** [comment]
It's fixed, but because of a different PR: https://github.com/CartoDB/d3.cartodb/pull/175
