### ISSUE TITLE
Map not showing up

### ISSUE THREAD

**Issue by saleiva** [CartoDB/d3.cartodb#163]
https://team.cartodb.com/u/saleiva/editor/de65584c-ed7c-11e2-a228-3085a9a9563c/embed?vector=true
No errors on the browser

**Comment by fdansv** [comment]
@saleiva that map is 404'ing

**Comment by saleiva** [comment]
added embed at the end of the URL

**Comment by rochoa** [comment]
@saleiva this seems to be working now, can you confirm?

**Comment by fdansv** [comment]
It does show up now, so we must have fixed it at some point.
