### ISSUE TITLE
Cannot pan the map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/d3.cartodb#165]
https://team.cartodb.com/u/saleiva/editor/c99b0680-0c4a-11e4-901c-0e10bcd91c2b/embed?vector=true

**Comment by rochoa** [comment]
Using a 2560x1440 display:

vector

``` js
document.querySelectorAll('*').length
1114547
```

raster

``` js
document.querySelectorAll('*').length
169
```

Does it makes sense to render 1M points client side? Shouldn't we use overviews for these scenarios?

**Comment by fdansv** [comment]
Yeah I've discussed this with Sergio already. This isn't really a bug, just beyond d3.cartodb's capabilities.

**Comment by saleiva** [comment]
Can we at least open a new ticket on detecting this and passing to raster?

**Comment by fdansv** [comment]
Hmmm, for now wouldn't it be weird to fallback to raster when we're explicitly asking for vector=true?

**Comment by rochoa** [comment]
I just created an issue at deep-insights, I'm not fully sure if that should live there or at cartodb.js repo but at least we are tracking it.
