### ISSUE TITLE
Incorrect layer offset with plain layers

### ISSUE THREAD

**Issue by rochoa** [CartoDB/d3.cartodb#177]
When a map, using named maps, has a plain layer like in https://team.cartodb.com/u/rochoa/editor/3ac1d804-663e-11e5-96f2-0e3bf0989add/embed. The plain layer is not being considered so the d3.cartodb is trying to use the cartocss from the incorrect layer: trying to use cartocss from layer[0] when it should retrieve from layer[1].

![screen shot 2016-04-28 at 16 35 38](https://cloud.githubusercontent.com/assets/45346/14889487/49c4d0ea-0d5f-11e6-95c2-5a7b5d65c618.png)

Example URL: https://team.cartodb.com/u/rochoa/editor/3ac1d804-663e-11e5-96f2-0e3bf0989add/embed?vector=true

I think this is related to https://github.com/CartoDB/d3.cartodb/issues/167.

cc @saleiva

**Comment by fdansv** [comment]
Fixed in CartoDB/cartodb.js#1252
