### ISSUE TITLE
marker-line is being drawn centered

### ISSUE THREAD

**Issue by saleiva** [CartoDB/d3.cartodb#179]
when vector the line is being drawn centered so widther line means smaller circle, while in raster its being drawn outside, so the size of the fill doesn't change.

We should unify to outside to maintain compatibility.

**Comment by saleiva** [comment]
You can compare this
https://team.cartodb.com/u/saleiva/editor/de65584c-ed7c-11e2-a228-3085a9a9563c/embed
vs
https://team.cartodb.com/u/saleiva/editor/de65584c-ed7c-11e2-a228-3085a9a9563c/embed?vector=true

**Comment by xavijam** [comment]
http://stackoverflow.com/questions/7241393/can-you-control-how-an-svgs-stroke-width-is-drawn

**Comment by fdansv** [comment]
The link above is a specification proposal, not a solution. At the moment there isn't a way to specify the origin of the stroke in svg that is supported by the browsers. There is a draft for the SVG standard:
https://svgwg.org/specs/strokes/#SpecifyingStrokeAlignment

@saleiva the only workaround that I can think of right now is changing the order of painting to stroke first. In your example this GIF would be the comparison:
![wololo](https://cloud.githubusercontent.com/assets/3707222/15391607/548a43b6-1dc2-11e6-92af-06b2bbe29270.gif)

**Comment by saleiva** [comment]
Does the trick tho... ;)
