### ISSUE TITLE
rendering is different from vector to raster

### ISSUE THREAD

**Issue by javisantana** [CartoDB/d3.cartodb#183]
This map look really different:

https://team.carto.com/u/mamataakella/builder/378193ce-197f-11e6-8c27-0ecfd53eb7d3/embed

**Comment by javisantana** [comment]
probably rendering order

**Comment by rochoa** [comment]
This map has a CartoCSS not supported by our current vector rendering implementation: `marker-multi-policy`. However, now it falls back to the raster version due to that limitation.
