### ISSUE TITLE
Map doesn't render anything

### ISSUE THREAD

**Issue by saleiva** [CartoDB/d3.cartodb#184]
Nothing is rendered when entering this map.
Js error: common_editor 3.js:14 Uncaught Error: function (a){return g.call(this,a,u)}

https://team.cartodb.com/u/dbryson/editor/7961a8f7-674e-4787-9dd3-872ef406e91a/embed?vector=true

It works perfectly in raster tho

cc/ @javisantana @fdansv

**Comment by fdansv** [comment]
Fixed in c5d3f3b434667910fb51c9743b7ee9c68c9ec0c6
