### ISSUE TITLE
Add public, layer-level interface for filtering

### ISSUE THREAD

**Issue by fdansv** [CartoDB/d3.cartodb#48]
Need to discuss this with @alonsogarciapablo

**Comment by pabletecodes** [comment]
Ok, time to get these filters to work! :v: 

Here's my proposal for the public API:

```
var layer = new L.CartoDBd3Layer({...});

layer.applyFilter(0, 'accept', { column: 'city', values: ['Madrid', 'Barcelona'] });
layer.applyFilter(0, 'accept', { column: 'city', values: 'all' });
layer.applyFilter(0, 'reject', { column: 'city', values: ['Madrid' ] });
layer.applyFilter(0, 'reject', { column: 'city', values: 'all' });
layer.applyFilter(0, 'range', { column: 'age', min: 0, max: 1000 });
```

The first parameter is the index of the "layer" inside of the vector layer. Having to deal with layer indexes and passing an integer parameter as the first value is not very elegant IMO, but we can make it prettier later.
