### ISSUE TITLE
Polygon/line events should not be fragmented into tiles

### ISSUE THREAD

**Issue by fdansv** [CartoDB/d3.cartodb#59]
In the long term this problem may be solving by stitching geometries, but for now it makes sense just to hash repeated features.

![before](https://cloud.githubusercontent.com/assets/3707222/11962491/7a10e2a4-a8e0-11e5-801c-f339033d8b7a.gif)

cc @javisantana

**Comment by javisantana** [comment]
I though this was fixed by https://github.com/CartoDB/d3.cartodb/pull/60

**Comment by fdansv** [comment]
It was, I just forgot to close the relevant issue :)
