### ISSUE TITLE
Provide ways to know if features have been loaded, when they have changed, and get features for a given sublayer

### ISSUE THREAD

**Issue by pabletecodes** [CartoDB/d3.cartodb#84]
As a user of the L.CartoDBd3Layer I want to able to:
1. Get notified when the features have been loaded or have changed (eg: initially, when the URL has been updated, or every time a filter has been applied).
   
   ```
   layer.bind('featuresChanged, function (features) {
      // I can work with the features
   });
   ```
2. Have a way to check if features have been loaded and be able to extract the features that have been previously loaded.
   
   ```
   if (layer.featuresLoaded()) {
     var features = layer.getFeatures();
     // use the features to get a list of categories, calculate the result of a formula, etc.
   )} else {
     // wait until features have been loaded/changed
     layer.bind('featuresChanged', function () {
       ...
     });
   }
   ```

@fdansv @rochoa @javisantana what do you guys think?

**Comment by fdansv** [comment]
I'm cool with the four of them. Within the logic of the layer, all these points are things that needed to be added as we bumped into them while integrating the library in CartoDB.js, and that's why they're not there yet. Let's get those there :+1:

**Comment by pabletecodes** [comment]
As discussed offline, the `features` argument of the `featuresChanged` callback, as well as the value returned by `layer.getFeatures`, will be an array with one entry for each of the (sub) layers that the d3 layer contains. Each of this array elements will contain all features in GeoJSON format. cc @fdansv
